name: MCInteractive
version: 2.3
author: ShortCircuit908
website: http://dev.bukkit.org/bukkit-plugins/MCInteractive/
main: com.shortcircuit.mcinteractive.MCInteractive
commands:
  breakout:
    description: Make the targeted block fire a message when powered
    usage: http://dev.bukkit.org/bukkit-plugins/mcinteractive/#w-create-a-trigger-block-breakout
  serial:
    description: Manage serial port connections
    usage: http://dev.bukkit.org/bukkit-plugins/mcinteractive/#w-manage-serial-connections-serial
  trackplayer:
    description: Toggle player tracking
    usage: http://dev.bukkit.org/bukkit-plugins/mcinteractive/#w-player-movement-tracking-trackplayer
  removetrigger:
    description: Remove the trigger from the targeted block
    usage: http://dev.bukkit.org/bukkit-plugins/mcinteractive/#w-remove-a-trigger-block-removetrigger