name: MCInteractive
version: 1.2
author: ShortCircuit908
website: http://dev.bukkit.org/bukkit-plugins/MCInteractive/
main: com.shortcircuit.mcinteractive.MCInteractive
commands:
  breakout:
    description: Make the targeted block fire a message when powered
    usage: /<command> <on:onStateMessage> <off:offStateMessage>
  serial:
    description: Manage serial port connections
    usage: /<command> <action:connect|disconnect> <port:comPort>
  trackplayer:
    description: Toggle player tracking
    usage: /<command> <player:playerName>